// frontend-react/src/ApiHealth.tsx
import { useEffect, useState } from 'react'

type Status = 'loading' | 'ok' | 'error'

const apiUrl: string = import.meta.env.VITE_API_URL ?? ''

export function ApiHealth() {
  const [status, setStatus] = useState<Status>('loading')
  const [appName, setAppName] = useState('')

  useEffect(() => {
    fetch(`${apiUrl}/api/health`)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        return res.json()
      })
      .then((data) => {
        setStatus(data.status === 'ok' ? 'ok' : 'error')
        setAppName(data.app ?? '')
      })
      .catch(() => setStatus('error'))
  }, [])

  return (
    <div>
      <p data-testid="status">API: {status}</p>
      {appName && <p data-testid="app-name">{appName}</p>}
    </div>
  )
}

// frontend-vue/src/components/ApiHealth.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'

const status = ref<'loading' | 'ok' | 'error'>('loading')
const appName = ref('')

const apiUrl: string = import.meta.env.VITE_API_URL ?? ''

onMounted(async () => {
  try {
    const res = await fetch(`${apiUrl}/api/health`)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data = await res.json()
    status.value = data.status === 'ok' ? 'ok' : 'error'
    appName.value = data.app ?? ''
  } catch {
    status.value = 'error'
  }
})
</script>

<template>
  <div class="api-health">
    <p data-testid="status">API: {{ status }}</p>
    <p v-if="appName" data-testid="app-name">{{ appName }}</p>
  </div>
</template>
